# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xunfang

# 挂载目录
VOLUME /home/xunfang
# 创建目录
RUN mkdir -p /home/xunfang
# 指定路径
WORKDIR /home/xunfang
# 复制jar文件到路径
COPY ./jar/xunfang-modules-file.jar /home/xunfang/xunfang-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","xunfang-modules-file.jar"]